import clusters
def getKmeans():
	blognames,words,data=clusters.readfile('blogdata.txt') 
	print "K value is 5"
	kclust=clusters.kcluster(data,k=5)
	print "\t\t"+str([blognames[r] for r in kclust[0]]) 
	print "\t\t"+str([blognames[r] for r in kclust[1]]) 
	print "\t\t"+str([blognames[r] for r in kclust[2]]) 
	print "\t\t"+str([blognames[r] for r in kclust[3]]) 
	print "\t\t"+str([blognames[r] for r in kclust[4]]) 
	print "K value is 10"
	kclust=clusters.kcluster(data,k=10)
	print "\t\t"+str([blognames[r] for r in kclust[0]]) 
	print "\t\t"+str([blognames[r] for r in kclust[1]]) 
	print "\t\t"+str([blognames[r] for r in kclust[2]]) 
	print "\t\t"+str([blognames[r] for r in kclust[3]]) 
	print "\t\t"+str([blognames[r] for r in kclust[4]]) 
	print "\t\t"+str([blognames[r] for r in kclust[5]]) 
	print "\t\t"+str([blognames[r] for r in kclust[6]]) 
	print "\t\t"+str([blognames[r] for r in kclust[7]]) 
	print "\t\t"+str([blognames[r] for r in kclust[8]]) 
	print "\t\t"+str([blognames[r] for r in kclust[9]]) 
	print "K value is 20"
	kclust=clusters.kcluster(data,k=20)
	print "\t\t"+str([blognames[r] for r in kclust[0]]) 
	print "\t\t"+str([blognames[r] for r in kclust[1]]) 
	print "\t\t"+str([blognames[r] for r in kclust[2]])
	print "\t\t"+str([blognames[r] for r in kclust[3]]) 
	print "\t\t"+str([blognames[r] for r in kclust[4]]) 
	print "\t\t"+str([blognames[r] for r in kclust[5]]) 
	print "\t\t"+str([blognames[r] for r in kclust[6]]) 
	print "\t\t"+str([blognames[r] for r in kclust[7]]) 
	print "\t\t"+str([blognames[r] for r in kclust[8]]) 
	print "\t\t"+str([blognames[r] for r in kclust[9]]) 
	print "\t\t"+str([blognames[r] for r in kclust[10]])
	print "\t\t"+str([blognames[r] for r in kclust[11]])
	print "\t\t"+str([blognames[r] for r in kclust[12]])
	print "\t\t"+str([blognames[r] for r in kclust[13]])
	print "\t\t"+str([blognames[r] for r in kclust[14]])
	print "\t\t"+str([blognames[r] for r in kclust[15]])
	print "\t\t"+str([blognames[r] for r in kclust[16]])
	print "\t\t"+str([blognames[r] for r in kclust[17]])
	print "\t\t"+str([blognames[r] for r in kclust[18]])
	print "\t\t"+str([blognames[r] for r in kclust[19]])
getKmeans()